services:
     server:
          build: .
          command: |
               bash -c " 
                    python src/db.py &&
                    python src/preprocess.py &&
                    python src/train.py && 
                    
                    uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --reload & 
                    
                    echo '等待API服务启动...' &&
                    while ! nc -z localhost 8000; do 
                         sleep 1 
                    done && 
                    
                    echo '开始执行测试...' &&
                    pytest src/tests/ --cov=src --cov-report=html && 
                    echo '测试完成...'
                    
                    tail -f /dev/null
                    "
          ports:
               - 8000:8000
          image: zwttt/ml-pipeline-3:latest
          environment:
               DECRYPT_FILE_PATH: ./secrets/db
               DECRYPT_PASSWORD: ${DECRYPT_PASSWORD}
               OUTPUT_FILE: ./env
               BASE_API_URL: http://localhost:8000
          depends_on:
               postgres:
                    condition: service_healthy

     postgres:
          image: postgres:latest
          ports:
               - 5432:5432
          environment:
               POSTGRES_DB: ${DB_NAME}
               POSTGRES_USER: ${DB_USER}
               POSTGRES_PASSWORD: ${DB_PASSWORD}
          healthcheck:
               test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
               interval: 5s
               timeout: 5s
               retries: 5
